# Generated by Django 4.2.11 on 2026-10-01 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('channel', models.CharField(default='live', max_length=32)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('raw_text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('canonical_name', models.CharField(max_length=200)),
                ('city', models.CharField(default='Lahore', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('base_url', models.URLField()),
                ('verified', models.BooleanField(default=False)),
                ('channel', models.CharField(default='live', max_length=32)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=32)),
                ('evidence_url', models.URLField(blank=True, max_length=1000)),
                ('evidence', models.TextField(blank=True)),
                ('evidence_status', models.CharField(choices=[('evidenced', 'evidenced'), ('contested', 'contested'), ('unevidenced', 'unevidenced')], default='evidenced', max_length=16)),
                ('is_contested', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='corpus.place')),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='corpus.society')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed', models.CharField(max_length=300)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('adjudication', models.CharField(default='unresolved', max_length=16)),
                ('stage', models.CharField(blank=True, max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.document')),
                ('resolved_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.place')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('size', 'size'), ('currency', 'currency'), ('category', 'category')], max_length=16)),
                ('source_form', models.CharField(max_length=64, unique=True)),
                ('canonical_value', models.CharField(max_length=64)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'indexes': [models.Index(fields=['dimension'], name='corpus_meas_dimensi_0efbf4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_type', models.CharField(max_length=64)),
                ('value', models.TextField()),
                ('as_of', models.DateField(blank=True, null=True)),
                ('raw_quote', models.TextField()),
                ('channel', models.CharField(default='live', max_length=32)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='corpus.document')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='corpus.place')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='corpus.source')),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.CharField(max_length=300, unique=True)),
                ('reason', models.TextField()),
                ('evidence_state', models.CharField(choices=[('confirmed', 'confirmed'), ('untested', 'untested'), ('document_scoped', 'document-scoped'), ('not_a_place', 'not-a-place')], default='confirmed', max_length=32)),
                ('evidence_note', models.TextField(blank=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.source')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='corpus.source'),
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.CharField(max_length=300)),
                ('evidence', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True, max_length=1000)),
                ('confirmed', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='corpus.place')),
            ],
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['level'], name='corpus_plac_level_eb8855_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('society', 'canonical_name')},
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['adjudication'], name='corpus_obse_adjudic_d04101_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['observed'], name='corpus_obse_observe_c285b4_idx'),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['place', 'fact_type'], name='corpus_fact_place_i_e664d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('source', 'url')},
        ),
        migrations.AddIndex(
            model_name='alias',
            index=models.Index(fields=['alias_text'], name='corpus_alia_alias_t_cace4c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together={('alias_text', 'place')},
        ),
    ]
