# Generated by Django 4.2.11 on 2026-10-01 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=8)),
                ('labels_observed', models.CharField(max_length=64)),
                ('source_count', models.PositiveSmallIntegerField(default=1)),
                ('verified', models.BooleanField(default=False)),
                ('single_source', models.BooleanField(default=True)),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_identities', to='corpus.place')),
                ('sources', models.ManyToManyField(blank=True, related_name='block_identities', to='corpus.source')),
            ],
            options={
                'unique_together': {('phase', 'letter')},
            },
        ),
    ]
