# Generated by Django 4.2.11 on 2026-10-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_blockidentity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactTypeCue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_type', models.CharField(max_length=64)),
                ('cue', models.CharField(max_length=64)),
                ('group', models.CharField(max_length=32)),
                ('corpus_count', models.PositiveIntegerField(default=0)),
                ('proven_in_corpus', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['fact_type'], name='corpus_fact_fact_ty_addee2_idx')],
                'unique_together': {('fact_type', 'cue')},
            },
        ),
    ]
