# Generated by Django 4.2.11 on 2026-10-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_facttypecue'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='published_dates',
            field=models.TextField(blank=True),
        ),
    ]
