# Generated by Django 4.2.11 on 2026-10-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_document_published_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='amount_pkr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='fact',
            name='file_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='fact',
            name='qualifier_status',
            field=models.CharField(choices=[('complete', 'complete'), ('partial', 'partial'), ('unknown', 'unknown')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='fact',
            name='size_marla',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddIndex(
            model_name='fact',
            index=models.Index(fields=['qualifier_status'], name='corpus_fact_qualifi_09e3b1_idx'),
        ),
    ]
